vim.keymap.set("n", "<leader>w", ":w<CR>")
vim.keymap.set("n", "<leader>q", ":q<CR>")
vim.keymap.set("n", "<leader>ff", "<cmd>Telescope find_files<cr>")
vim.keymap.set("n", "<leader>fg", "<cmd>Telescope live_grep<cr>")
vim.keymap.set("n", "<C-n>", function()
  require("snacks.explorer")()
end, { desc = "Toggle file explorer" })

vim.keymap.set("n", "<leader>sf", function()
  require("snacks.picker").files()
end, { desc = "Snacks find files" })
